# Generated by Django 5.2 on 2025-06-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
