# Generated by Django 5.2 on 2025-04-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_riderlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike Taxi'), ('auto', 'Auto Rickshaw'), ('car', 'Car'), ('truck', 'Truck'), ('loading', 'Loading Vehicle')], max_length=20),
        ),
    ]
