# Generated by Django 5.2 on 2025-05-31 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_ride_cancel_reason'),
        ('driver', '0004_driver_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('penalty_points', models.IntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driver')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.ride')),
            ],
        ),
    ]
