# Generated by Django 5.2 on 2025-04-24 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('drop_lat', models.FloatField()),
                ('drop_lng', models.FloatField()),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike Taxi'), ('auto', 'Auto Rickshaw'), ('car', 'Car'), ('truck', 'Truck'), ('loading', 'Loading Vehicle')], max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
