# Generated by Django 5.2 on 2025-04-25 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_ride_status'),
        ('driver', '0003_alter_driver_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.driver'),
        ),
    ]
