# Generated by Django 5.2 on 2025-05-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
